import type { Metadata } from "next";
import { ToastProvider } from "@components/providers/ToastProvider";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="h-screen">
        <ToastProvider />
        {children}
      </body>
    </html>
  );
}
